### ISSUE TITLE
Problem with custom Notion domain

### ISSUE THREAD

**Issue by EstebanMunoz** [hk21702/YA-GCal-Notion-Sync-Script#20] opened 2022-09-20 18:01 UTC
Hi. I was trying to setup this sync but I got an error.

```
Error: {"object":"error","status":400,"code":"invalid_request_url","message":"Invalid request URL."}
notionFetch	        @ main.gs:421
deleteCancelledEvents	@ main.gs:704
main	                @ main.gs:24
```

I realized the function `parseNotionProperties()` is not getting `DATABASE_ID` as expected (`workspace-domain/database-id` instead of `database-id`). I am using a custom domain with a hyphen, in case it is relevant to the regex. I manually changed the `DATABASE_ID` value and it worked fine.

**Comment by hk21702** [comment] 2022-09-27 10:14
Do you mind giving an example of a link to a shared database? You can change up your domain and the database id a bit to anonymize it, I just want to do some testing. I thought custom domains should have been working since it was an issue with some users before and was then fixed, so it might be something specific to your case.

**Comment by hk21702** [comment] 2022-11-28 06:26
I haven't been able to reproduce this using pseudo custom domains with and without hyphens. Since I haven't gotten any other reports of a similar issue and haven't been given an example, I'm going to close this issue.

**Closed by hk21702** 2022-11-28 06:26 UTC
Labels: bug, question
