### ISSUE TITLE
Whole-day event - offset by one day to get the end date

### ISSUE THREAD

**Issue by sykin13** [hk21702/YA-GCal-Notion-Sync-Script#24] opened 2022-09-29 02:26 UTC
L497 Comment said offset by one day to get the end date. But the code seems to be missing, which leads to the problem of extending the days of whole-day events on GCal after synchronization.

**Comment by hk21702** [comment] 2022-09-29 17:05
This is a known thing relating to time zones being funky in Google apps script. Some people had success in fixing it by going into their project settings and changing to a different "timezone" that has the same GMT offset such that the actual time doesn't really change in reality.  I'll add this to the FAQ, but a straightforward fix is unfortunately unlikely.

**Comment by mortyccp** [comment] 2022-09-30 16:27
I think this is caused by Google Calendar returning full date event with start and end date not being the same. 🤔

<img width="1916" alt="image" src="https://user-images.githubusercontent.com/4152518/193315100-32959884-c1af-41df-9b5a-097570e68c3c.png">

**Comment by hk21702** [comment] 2022-11-24 04:04
Fundamentally yes, it is caused by that. The script tries to fix it, but because of weirdness and inconsistencies of how the API and apps script seem to work with different time zones, results are inconsistent. I'm going to close this issue for now, maybe reopen it if I get around to implementing a better fix, but for now, if anyone runs into this issue refer to this wiki entry: https://github.com/hk21702/YA-GCal-Notion-Sync-Script/wiki/FAQ-&-Common-Errors#full-day-gcal-events-show-up-as-two-day-events-in-notion

**Closed by hk21702** 2022-11-24 04:04 UTC
Labels: bug, documentation
